### ISSUE TITLE
Using PL-AVOD pre train to infer on MOT dataset

### ISSUE THREAD

**Issue by dmatos2012** [mileyan/pseudo_lidar#39]
Hello,

Your code works perfectly and I have been able to evaluate your pre trained model. However, I want to use your Pseudo-LiDar pre trained model on AVOD to generate 3D detections on KITTI MOT dataset rather than the Object detection dataset, so question

1. Do I need to train from scratch in order to generate the new Pseudo Lidar and planes for the new dataset?

I thought I could do as usual and just provide the different images and that would be enough, but I get asked for the planes folder but do not know if using the previous one is correct, even tho I am using a pre trained model and not training.
Thanks.

**Comment by mileyan** [comment]
Hi @dmatos2012 . I suggest that you re-train the model on KITTI MOT dataset, since there might be some overlap between KITTI MOT testing data and KITTI 3D detection training data. Yes, you have to generate the planes. You can use [kitti_process_RANSAC.py](https://github.com/mileyan/pseudo_lidar/blob/master/preprocessing/kitti_process_RANSAC.py) to generate ground planes.

**Comment by dmatos2012** [comment]
Hi @mileyan . Thank you for your answer. That answers my question,therefore closing the issue.
